### ISSUE TITLE
parsing errors on rezeptewiki.org

### ISSUE THREAD

**Issue by bitboxer** [nricciar/wikicloth#40]
I am trying to parse the data from rezeptewiki, a german wiki for recipes. I found two errors that crash the parser on 43 documents of that wiki.
# Template in table definition

```
Unknown error on line 11 row 4: WikiCloth::WikiBuffer-->width="100%"-->border="2" cellspacing="1" cellpadding="2" rules="all" style="margin:1em 1em 1em 0; border:solid 1px #d6d6d6; border-collapse:collapse; background-color:#fffbf5; empty-cells:show; width="500px"
DAMAGE : 16452 - Zubereitung:Saisonkalender Obst
undefined method `[]' for nil:NilClass
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth/wiki_buffer/table.rb:108:in `new_char'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth/wiki_buffer.rb:158:in `add_char'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth/wiki_buffer.rb:159:in `add_char'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:138:in `add_current_char'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:86:in `block in render'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:86:in `each_char'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:86:in `render'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:107:in `to_html'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth/parser.rb:89:in `method_missing'
```

This can be found in this document: http://www.rezeptewiki.org/wiki/Zutat:Nova
# Problems with sections

I don't know why, but on a few documents the section system gets messed up. 

```
undefined method `<<' for nil:NilClass
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:44:in `block in load'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:39:in `each_line'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:39:in `load'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth.rb:28:in `initialize'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth/parser.rb:14:in `new'
/Users/bodo/.rvm/gems/ruby-1.9.3-p125/gems/wikicloth-0.8.0/lib/wikicloth/parser.rb:14:in `initialize'
```

This can be found in this document: http://www.rezeptewiki.org/wiki/Gebackene_Innviertler_Zwetschgenkn%C3%B6del

**Comment by fabn** [comment]
Also getting this issue

**Comment by jfouse** [comment]
I just hit an error that I suspect might be related to your "section issues" comment, @nricciar.  Here's the reduced sample text that triggers it:

> ===A===
> ==A==
> =A=

Your section-parsing block in lib/wikicloth.rb:37-47 makes some assumptions about the way sections *should* progress, but you can't really rely on that in real world data unfortunately.  With the above example text, parsing line 3 at code line 40 causes root to pop its only item (because $1 is 1 and depth is 2), so two lines later root.last is nil, leading to the second error @bitboxer pasted above.  

It's one thing if you want to say, "that's not valid mediawiki markup", but then just render it as-is as plain text.  Don't make my app blow chunks.  :D
